if 1 != 1:
  print("test")
  print("asd")
else:
  print("qwe")
  print("rty")
a = "uio"
print(a)
print("jsndf")
print("8271")
print("dfga")
print("srido")
print("inkrgfn")
print("943nunm")
print("siodjknf")
print("klmsd")
print("qopj")
print("3j30")
print("94m-m0v3")
print("ewotpmj")
print("qwlqwee")
print("erjn")
print("ertdwq")
print("ejrn")
print("reioj")
print("jkk")
print("zxb")
if 1 == 1:
  print("1"+ +"+"+ +"1"+ +"="+ +"3")
